dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tst.txt
  - pip install .
script:
  - coverage run --source=e2j2 setup.py test 
  - coveralls
  - behave
